### ISSUE TITLE
dictionary API functionality

### ISSUE THREAD

**Issue by samascher** [m2creger/the-wordsmither#4]
hey marshall - nice job again. any chance you can take another stab at the dictionary API if you have a moment?? i think it'd GREATLY increase the awesomeness of your game by feeding more options for words into each category. you're killing it!! let me know if i can help you with this at all - i haven't worked with APIs yet but i'm super stoked to :)

**Comment by m2creger** [comment]
Thanks for the feedback. I got the API working
