### ISSUE TITLE
Results Page, consider radio buttons vs. checkboxes

### ISSUE THREAD

**Issue by jeffDevelops** [m2creger/the-wordsmither#5]
Hey, Marshall! 

I was playing your game and I got to the results page, where we're rejecting or accepting our answers vs. the AI's answers. It seems a little counterintuitive that I can both reject and accept an answer, so you might want to do radio buttons there instead. What happens in your logic if a user checks both boxes?

Great job on your project! 
Jeff

**Comment by m2creger** [comment]
I put in toggle buttons and got rid of reject. Made it a lot cleaner. Thanks for the suggestion.
